language: python
sudo: false
python:
- '2.7'
addons:
  apt:
    sources:
    - libgraphviz-dev
before_install:
- wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
- chmod +x miniconda.sh
- "./miniconda.sh -b"
- export PATH=/home/travis/miniconda/bin:$PATH
- conda update --yes conda
install:
- conda install --yes python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib sympy networkx
  nose h5py
- pip install -i https://pypi.binstar.org/pypi/simple pygraphviz
- wget http://mmbios.org/index.php/bionetgen-2-2-5-stable/bionetgen-2-2-5-stable-zip?format=raw
  -O BioNetGen-2.2.5-stable.zip
- unzip BioNetGen-2.2.5-stable.zip
- export BNGPATH=`pwd`/BioNetGen-2.2.5-stable
- git clone https://github.com/lolab-vu/pysb.git -b dev --single-branch
- export PYTHONPATH=$PYTHONPATH:`pwd`/pysb
script: nosetests
notifications:
  slack:
    secure: PGpnfjG88C/FbOKm/Pf9/fnNCQ2S+uuvs3nm+AQ9FhLMV965D+CNNJj6cFB1rs1Ozj4UfZSAzYkgDHRy0zpihtoT48+llRMeC8o0YPD8KEz0vfdm9813PQ+n6QMeWLTDtyVpzWhU4kgx1u7EMw2tYBRQYoPz5bWPR0Z7/9aRmTKdh4Mny7dgLU5JifnfPifWzPG5NB3qIY20kmeOMUwWbhoS5v+a4BWvfw1d0bIRmBf9a4w4vsvktpW5v6T4EtSxndgMTkm8BeAWYxsemZq4tFqajWEIcECRR5H33iIz8jcG9rSV7bbjgs3gZm4R+PQO9MG6pYpOeg/r+ThNbXRWoO5jiBYwgkIZbL1BcT52F/3E2dt1mcHLCvGLTxaMT0Le3CDFh8Z/wM2axf8vDKBBbRzBw8gY+Z9g18qutC2qyociKcuYEOXYXTrNGt7Iq79E/aquQ/CLtoUlReecAg/1pPZdXhApnCKBDFZbyIzVaZtIOFzFU7xV9+2vxbcbn1GI4KgaAkNNw+azLwU/Tlhc6iyhvxVgzNyULEF0ukpVi3/zfebrplhrZupkohUrSomcqFjjhiwojcp+UjTyHXmYRihRn7PINAaFHc95fAnOUwSwii3Qgf1ANcyWpfEmQjdjderz6ElXbDQ/zv0fnD29nkhJAmNYcoIU3FlVhYdGaDA=
