from exported_nnrm import model
from pysb.core import *
from pysb.bng import *
from pysb.integrate import *
import matplotlib.pyplot as plt
import numpy as np


Observable('one', TNF(brec=1) % TNFR(blig=1, brip=None))

Observable('two', TNF(brec = 1) % TNFR(blig=1, brip=2) % TRADD(brec = 2, brip = None, bDD1=None, bDD2=None))

Observable('three', TNF(brec = 1) % TNFR(blig=1, brip=2) % TRADD(brec = 2, brip = 3, bDD1=None, bDD2=None)
           % RIP1(bscf=3, btraf=None, bub1=None, bub2=None, bub3=None,bDD = None,bRHIM=None,bMLKL=None, state='unmod'))

Observable('four', TNF(brec = 1) % TNFR(blig=1, brip=2) % TRADD(brec = 2, brip = 3, bDD1=None, bDD2=None) %
           RIP1(bscf=3, btraf=4, bub1=None, bub2=None, bub3=None,bDD = None,bRHIM=None,bMLKL=None, state='unmod') % TRAF(brip=4, bciap=None, state='unmod'))

Observable('five', TNF(brec = 1) % TNFR(blig=1, brip=2) % TRADD(brec = 2, brip = 3, bDD1=None, bDD2=None) %
           RIP1(bscf=3, btraf=4, bub1=None, bub2=None, bub3=None,bDD = None,bRHIM=None,bMLKL=None, state='K63ub') % TRAF(brip=4, bciap=5, bcyld =None, state='unmod') % cIAP(btraf = 5))

Observable('six', TNF(brec = 1) % TNFR(blig=1, brip=2) % TRADD(brec = 2, brip = 3, bDD1=None, bDD2=None) % RIP1(bscf=3, btraf=4, bub1=6, bub2=None, bub3=None,bDD = None,bRHIM=None,bMLKL=None, state='K63ub')
           % TRAF(brip=4, bciap=5, bcyld =None, state='unmod') % cIAP(btraf = 5) % LUBAC(brip = 6))

Observable('RIP1deub', RIP1(state='deub'))
# Observable('TAK1',TAK1(brip = ANY))
Observable('TAK1b', TNF(brec = 1) % TNFR(blig=1, brip=2) % TRADD(brec = 2, brip = 3, bDD1=None, bDD2=None) % RIP1(bscf=3, btraf=4, bub1=6, bub2=7, bub3=8,bDD = None,bRHIM=None,bMLKL=None, state='K63ub')
           % TRAF(brip=4, bciap=5, bcyld =None, state='unmod') % cIAP(btraf = 5) % LUBAC(brip = 6) % NEMO(brip=7) % TAK1(brip=8))
Observable('IKK_obs', IKK(bind=None, bnemo = None, state = 'A'))
Observable('IKKb', TNF(brec = 1) % TNFR(blig=1, brip=2) % TRADD(brec = 2, brip = 3, bDD1=None, bDD2=None) % RIP1(bscf=3, btraf=4, bub1=6, bub2=7, bub3=8,bDD = 9,bRHIM=None,bMLKL=None, state='K63ub') %
           TRAF(brip=4, bciap=5, bcyld =None, state='unmod') % cIAP(btraf = 5) % LUBAC(brip = 6) % NEMO(brip=7) % TAK1(brip=8) % IKK(bind=9, bnemo = None, state = 'I'))


Observable('RIP1RIP3po4', RIP1(bscf = None, bub1 = None, bub2 = None, bub3 = None, bDD=None, btraf=None, bMLKL = None, bRHIM = 5, state = 'po4')
           % RIP3(bRHIM=5, bDD = None, state='po4'))
Observable('MLKLa', MLKL(bRHIM=None, state='active'))

Observable('RIPMLKL', RIP1(bscf = None, bub1 = None, bub2 = None, bub3 = None, bDD=None, btraf=None, bMLKL = 1, bRHIM = 5, state = 'po4')
           % RIP3(bRHIM=5, bDD = None, state='po4') % MLKL(bRHIM=1, state='unmod'))



# Defining Observables
Observable('TNFR_TNF', TNFR(blig=ANY))
Observable('TRADD_CompI', TRADD(brec=ANY))
Observable('RIP1_CompI', TNFR() % RIP1())
Observable('RIP1ub', RIP1(state='K63ub'))
# Observable('TRAF_CompI', TRAF(brip=ANY) % RIP1(btraf=ANY))
# Observable('Obs_TRAF_ComplexI', TRAF(brip=ANY) % RIP1(btraf=ANY))
Observable('Ubiquitylated_ComplexI', RIP1(state='K63ub'))
Observable('MAPK_activity', MAPK(state='active'))
Observable('RIP1deub', RIP1(state='deub'))
Observable('Obs_ComplexII', TRADD(brec=None, brip=1) % RIP1(bscf=1, btraf=None, bub1=None, bub2=None, bub3=None, state='deub'))
Observable('TNFR_endocytosis', TNF(brec=3) % TNFR(blig=3) % RIP1(btraf=None, bub1=None, bub2=None, bub3=None, state='deub'))
Observable('CYLD_CompI_1', RIP1(bscf=ANY, bub2=2, bub3=None, state='K63ub') % CYLD(brip=2))
Observable('CYLD_CompI_2', RIP1(bscf=ANY, btraf=3, bub2=2, bub3=None, state='K63ub') % CYLD(brip=2) % TRAF(brip=3, state='K63ub'))
Observable('NFkBn_obs', NFkB(loc='N'))
Observable('NFkB_obs', NFkB(loc='C'))
Observable('IkBa_obs', IkBa(loc='C', state='active'))
Observable('IkBb_obs', IkBb(loc='C', state='active'))
Observable('IkBe_obs', IkBe(loc='C', state='active'))
Observable('IkBd_obs', IkBd(loc='C', state='active'))
Observable('IkBan_obs', IkBa(ikk=None, nfkb=None, loc='N', state='active'))
Observable('IkBbn_obs', IkBb(ikk=None, nfkb=None, loc='N', state='active'))
Observable('IkBen_obs', IkBe(ikk=None, nfkb=None, loc='N', state='active'))
Observable('IkBdn_obs', IkBd(ikk=None, nfkb=None, loc='N', state='active'))
Observable('IkBaNFkB_obs', IkBa(ikk=None, nfkb=1, loc='C', state='active') % NFkB(ikb=1, loc='C'))
Observable('IkBbNFkB_obs', IkBb(ikk=None, nfkb=1, loc='C', state='active') % NFkB(ikb=1, loc='C'))
Observable('IkBeNFkB_obs', IkBe(ikk=None, nfkb=1, loc='C', state='active') % NFkB(ikb=1, loc='C'))
Observable('IkBdNFkB_obs', IkBd(ikk=None, nfkb=1, loc='C', state='active') % NFkB(ikb=1, loc='C'))
Observable('IkBaNFkBn_obs', IkBa(ikk=None, nfkb=1, loc='N', state='active') % NFkB(ikb=1, loc='N'))
Observable('IkBbNFkBn_obs', IkBb(ikk=None, nfkb=1, loc='N', state='active') % NFkB(ikb=1, loc='N'))
Observable('IkBeNFkBn_obs', IkBe(ikk=None, nfkb=1, loc='N', state='active') % NFkB(ikb=1, loc='N'))
Observable('IkBdNFkBn_obs', IkBd(ikk=None, nfkb=1, loc='N', state='active') % NFkB(ikb=1, loc='N'))
Observable('RIP1_obs',RIP1(bscf=None, btraf=None, bub1=None, bub2=None, bub3=None, state='unmod'))
Observable('RIP3_obs', RIP3(bRHIM=None, bDD = None, state='unmod'))
Observable('MLKL_obs', MLKL(bRHIM=None, state='unmod'))
Observable('MLKLa_obs', MLKL(bRHIM=None, state='active'))
Observable('RIP13_obs', RIP1(bDD=ANY, bRHIM=1, state='unmod') % RIP3(bRHIM=1, bDD = None, state='unmod'))
Observable('RIP13po4_obs', RIP1(bscf = None, bub1 = None, bub2 = None, bub3 = None, bDD=None, btraf=None, bMLKL = None, bRHIM = 5, state = 'po4')% RIP3(bRHIM=5, bDD = None, state='po4'))
Observable('TNF_obs', TNF(brec = ANY))
Observable('RIPk63_obs',  RIP1(bscf=None, bub1=None, state='K63ub'))
Observable('TNFR_TRADD', TNFR(blig=None, brip=1) % TRADD(brec=1, brip=None))
Observable('CI_k63_obs', TRADD(brec=None, brip=1, state='K63ub') % RIP1(bscf=1, btraf=2, state='K63ub') % TRAF(brip=2, bciap=3, state='K63ub') % cIAP(btraf=3))
Observable('IkBamrna', IkBa_mRNA())
Observable('IKK_obs', IKK(bind=None))
# Observable('IKKany', IKK(bind = ANY))
Observable('CI', TNF(brec = 1) % TNFR(blig=1, brip=2) % TRADD(brec=2, brip=3) % RIP1(bscf=3, btraf=4, bub1=None, bub2=None, bub3=None, state='K63ub') % TRAF(brip=4, bciap=5, state='unmod') % cIAP(btraf = 5))

generate_network(model)
generate_equations(model)
#
# # # print(model.initials)
#


tspan = np.linspace(0, 1440, 1441)
x = odesolve(model,tspan,verbose=True)

plt.figure()
plt.plot(tspan/60, x['RIP1deub'], label="RIP1deub")
# plt.plot(tspan, pandas_df['NFkBn'][0:721], label = 'NFkBn')
plt.xlabel("Time (in hr)", fontsize=16)
plt.ylabel("Molecules per Cell", fontsize=16)
# plt.ylim(ymin = 0, ymax = 0.00000008)
plt.legend(loc=0)
# plt.title('RIP13po4')
#
plt.figure()
plt.plot(tspan/60, x['IKK_obs'], label="IKK")
# plt.plot(tspan, pandas_df['NFkBn'][0:721], label = 'NFkBn')
plt.xlabel("Time (in hr)", fontsize=16)
plt.ylabel("Molecules per Cell", fontsize=16)
# plt.ylim(ymin = 0, ymax = 0.00000008)
plt.legend(loc=0)
#
plt.figure()
plt.plot(tspan/60, x['RIPMLKL'], label="RIPMLKL")
# plt.plot(tspan, pandas_df['NFkBn'][0:721], label = 'NFkBn')
plt.xlabel("Time (in hr)", fontsize=16)
plt.ylabel("Molecules per Cell", fontsize=16)
# plt.ylim(ymin = 0, ymax = 0.00000008)
plt.legend(loc=0)

plt.figure()
plt.plot(tspan/60, x['RIP1RIP3po4'], label="RIP1RIP3po4")
# plt.plot(tspan, pandas_df['NFkBn'][0:721], label = 'NFkBn')
plt.xlabel("Time (in hr)", fontsize=16)
plt.ylabel("Molecules per Cell", fontsize=16)
# plt.ylim(ymin = 0, ymax = 0.00000008)
plt.legend(loc=0)

plt.figure()
plt.plot(tspan/60, x['MLKLa'], label="MLKLa")
# plt.plot(tspan, pandas_df['NFkBn'][0:721], label = 'NFkBn')
plt.xlabel("Time (in hr)", fontsize=16)
plt.ylabel("Molecules per Cell", fontsize=16)
# plt.ylim(ymin = 0, ymax = 0.00000008)
plt.legend(loc=0)

plt.show()
plt.figure()
plt.plot(tspan/60, x['IkBa_obs'], label="IkBa")
# plt.plot(tspan, pandas_df['NFkBn'][0:721], label = 'NFkBn')
plt.xlabel("Time (in hr)", fontsize=16)
plt.ylabel("Molecules per Cell", fontsize=16)
# plt.ylim(ymin = 0, ymax = 0.00000008)
plt.legend(loc=0)
plt.title('IkBa')

plt.figure()
plt.plot(tspan/60, x['IkBb_obs'], label="IkBb")
# plt.plot(tspan, pandas_df['NFkBn'][0:721], label = 'NFkBn')
plt.xlabel("Time (in hr)", fontsize=16)
plt.ylabel("Molecules per Cell", fontsize=16)
# plt.ylim(ymin = 0, ymax = 0.00000008)
plt.legend(loc=0)
plt.title('IkBb')

plt.figure()
plt.plot(tspan/60, x['IkBe_obs'], label="IkBe")
# plt.plot(tspan, pandas_df['NFkBn'][0:721], label = 'NFkBn')
plt.xlabel("Time (in hr)", fontsize=16)
plt.ylabel("Molecules per Cell", fontsize=16)
# plt.ylim(ymin = 0, ymax = 0.00000008)
plt.legend(loc=0)
plt.title('IkBe')

plt.figure()
plt.plot(tspan/60, x['IkBd_obs'], label="IkBd")
# plt.plot(tspan, pandas_df['NFkBn'][0:721], label = 'NFkBn')
plt.xlabel("Time (in hr)", fontsize=16)
plt.ylabel("Molecules per Cell", fontsize=16)
# plt.ylim(ymin = 0, ymax = 0.00000008)
plt.legend(loc=0)
plt.title('IkBd')
# # plt.show()
# #

#
# last_conc = [x[y][-1] for y in ['__s%d' %i for i in np.arange(len(model.species))]]
# print(last_conc)
#
# first_conc = [x[y][0] for y in ['__s%d' %i for i in np.arange(len(model.species))]]
# print(first_conc)
#
#
# # print("IkBmrna conc")
# # print(x['IkBamrna'])
# #
# # print('IKK conc')
# # print(x['IKK_obs'])
# # print(x['IKKany'])
#
# # # with PdfPages('multipage_pdf.pdf') as pdf:
plt.figure()
plt.plot(tspan/60, x['CI'], label="CI")
# plt.plot(tspan, pandas_df['NFkBn'][0:721], label = 'NFkBn')
plt.xlabel("Time (in hr)", fontsize=16)
plt.ylabel("Molecules per Cell", fontsize=16)
# plt.ylim(ymin = 0, ymax = 0.00000008)
plt.legend(loc=0)
plt.title('CI')
# #
# # plt.figure()
# # plt.plot(tspan/60, x['CI_k63_obs'], label="CI_k63")
# # # plt.plot(tspan, pandas_df['NFkBn'][0:721], label = 'NFkBn')
# # plt.xlabel("Time (in hr)", fontsize=16)
# # plt.ylabel("Molecules per Cell", fontsize=16)
# # # plt.ylim(ymin = 0, ymax = 0.00000008)
# # plt.legend(loc=0)
# # plt.title('CI_k63')
# #
# #
plt.figure()
plt.plot(tspan/60, x['TNF_obs'], label="TNF")
# plt.plot(tspan, pandas_df['NFkBn'][0:721], label = 'NFkBn')
plt.xlabel("Time (in hr)", fontsize=16)
plt.ylabel("Molecules per Cell", fontsize=16)
# plt.ylim(ymin = 0, ymax = 0.00000008)
plt.legend(loc=0)
plt.title('TNF')
# # pdf.savefig()
# # plt.close()
#
# plt.figure()
# plt.plot(tspan/60, x['RIP1ub'], label="RIP1ub")
# # plt.plot(tspan, pandas_df['NFkBn'][0:721], label = 'NFkBn')
# plt.xlabel("Time (in hr)", fontsize=16)
# plt.ylabel("Molecules per Cell", fontsize=16)
# # plt.ylim(ymin = 0, ymax = 0.00000008)
# plt.legend(loc=0)
# plt.title('RIP1')
# # pdf.savefig()
# # plt.close()
#
#
plt.figure()
plt.plot(tspan/60, x['RIP13po4_obs'], label="RIP13po4")
# plt.plot(tspan, pandas_df['NFkBn'][0:721], label = 'NFkBn')
plt.xlabel("Time (in hr)", fontsize=16)
plt.ylabel("Molecules per Cell", fontsize=16)
# plt.ylim(ymin = 0, ymax = 0.00000008)
plt.legend(loc=0)
plt.title('RIP13po4')
# # # pdf.savefig()
# # # plt.close()
# #
# plt.figure()
# plt.plot(tspan/60, x['NFkB_obs'], label="NFkB")
# # plt.plot(tspan, pandas_df['NFkBn'][0:721], label = 'NFkBn')
# plt.xlabel("Time (in hr)", fontsize=16)
# plt.ylabel("Molecules per Cell", fontsize=16)
# plt.ylim(ymin = 0, ymax = 1000)
# plt.legend(loc=0)
# plt.title('NFkB')
#
plt.figure()
plt.plot(tspan/60, x['NFkBn_obs'], label="NFkBn")
# plt.plot(tspan, pandas_df['NFkBn'][0:721], label = 'NFkBn')
plt.xlabel("Time (in hr)", fontsize=16)
plt.ylabel("Molecules per Cell", fontsize=16)
# plt.ylim(ymin = 0, ymax = .0002)
plt.legend(loc=0)
plt.title('NFkBn')
# # pdf.savefig()
# # plt.close()
#
plt.figure()
plt.plot(tspan/60, x['IkBaNFkB_obs'], label="IkBaNFkB")
# plt.plot(tspan, pandas_df['NFkBn'][0:721], label = 'NFkBn')
plt.xlabel("Time (in hr)", fontsize=16)
plt.ylabel("Molecules per Cell", fontsize=16)
# plt.ylim(ymin = 0, ymax = .0002)
plt.legend(loc=0)
plt.title('IkBaNFkB')
# pdf.savefig()
# plt.close()

plt.figure()
plt.plot(tspan/60, x['NFkBn_obs'], label="NFkBn")
# plt.plot(tspan, pandas_df['NFkBn'][0:721], label = 'NFkBn')
plt.xlabel("Time (in hr)", fontsize=16)
plt.ylabel("Molecules per Cell", fontsize=16)
# plt.ylim(ymin = 0, ymax = 0.00000008)
plt.legend(loc=0)
plt.title('NFkBn')
# pdf.savefig()
# plt.close()

#
plt.figure()
plt.plot(tspan/60, x['RIPk63_obs'], label="RIPk63")
# plt.plot(tspan, pandas_df['NFkBn'][0:721], label = 'NFkBn')
plt.xlabel("Time (in hr)", fontsize=16)
plt.ylabel("Molecules per Cell", fontsize=16)
# plt.ylim(ymin = 0, ymax = 0.00000008)
plt.legend(loc=0)
plt.title('RIPk63')
#
plt.figure()
plt.plot(tspan/60, x['IKK_obs'], label="IKK")
# plt.plot(tspan, pandas_df['NFkBn'][0:721], label = 'NFkBn')
plt.xlabel("Time (in hr)", fontsize=16)
plt.ylabel("Molecules per Cell", fontsize=16)
# plt.ylim(ymin = 0, ymax = 0.00000008)
plt.legend(loc=0)
plt.title('IKK')
#
plt.figure()
plt.plot(tspan/60, x['IkBamrna'], label="IkBamrna")
# plt.plot(tspan, pandas_df['NFkBn'][0:721], label = 'NFkBn')
plt.xlabel("Time (in hr)", fontsize=16)
plt.ylabel("Molecules per Cell", fontsize=16)
# plt.ylim(ymin = 0, ymax = 0.00000008)
plt.legend(loc=0)
plt.title('mrna')
# # # pdf.savefig()
# # # plt.close()
# #
plt.figure()
plt.plot(tspan/60, x['MLKLa_obs'], label="MLKLa")
# plt.plot(tspan, pandas_df['NFkBn'][0:721], label = 'NFkBn')
plt.xlabel("Time (in hr)", fontsize=16)
plt.ylabel("Molecules per Cell", fontsize=16)
# plt.ylim(ymin = 0, ymax = 0.00000008)
plt.legend(loc=0)
plt.title('MLKLa')
# pdf.savefig()
# plt.close()

plt.show()